server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spring-alibaba-ai-customer-service

  # 数据库配置 (H2内存数据库用于演示)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

  # Thymeleaf配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

# Spring Cloud Alibaba AI配置
spring:
  cloud:
    alibaba:
      ai:
        # 通义千问配置
        tongyi:
          chat:
            options:
              # 模型名称
              model: qwen-turbo
              # 温度参数，控制回答的随机性
              temperature: 0.7
              # 最大token数
              max-tokens: 1000
              # top-p参数
              top-p: 0.8
          # API密钥 (请替换为您的实际密钥)
          api-key: ${TONGYI_API_KEY:your-api-key-here}

# 应用自定义配置
customer-service:
  # 默认欢迎消息
  welcome-message: "您好！我是智能客服助手，有什么可以帮助您的吗？"
  # 系统提示词
  system-prompt: |
    你是一个专业的客服助手，请遵循以下规则：
    1. 保持友好和专业的语调
    2. 尽可能提供准确和有用的信息
    3. 如果不确定答案，请诚实地说明
    4. 对于复杂问题，建议用户联系人工客服
    5. 回答要简洁明了，避免过于冗长
  # 会话超时时间（分钟）
  session-timeout: 30

# 日志配置
logging:
  level:
    com.example.customerservice: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
